spring:
  application:
    name: pagamentos

  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}?authSource=${MONGO_DB_AUTH}

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.springframework.core.env: DEBUG

server:
  forward-headers-strategy: framework
  servlet:
    context-path: ${PATH_PREFIX:/}
  port: 8090
  compression:
    enabled: true
    min-response-size: 2048
    mime-types:
      - application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true
    filter: true
  api-docs:
    path: /api-docs
